IUT_RS/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path('home/', views.home.as_view(), name='home_'),
                  path('mdeditor/', include('mdeditor.urls')),
                  path('blogs/', include('blogs.urls')),
                  path('achievements/', include('achievements.urls')),
                  path('activity/', include('activity.urls')),
                  path('projects/', include('projects.urls')),
                  path('executive_committee/', views.ExecutiveCommittee.as_view(), name='executive_committee'),
                  path('about/', views.about.as_view(), name='about'),
                  path('admin_panel/', include('admin_panel.urls')),
                  path('', views.home.as_view(), name='home'),
                  path('leaderboard/', views.leaderboard.as_view(), name='leaderboard'),


              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path

from . import views

app_name = 'blogs'

urlpatterns = [
    path('', views.index, name='blogs'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create_blog/', views.createBlog, name='create_blog'),
    path('edit_blog/<int:pk>', views.editBlog.as_view(), name='edit_blog'),
    path('update_blog/<int:pk>', views.updateBlog, name='update_blog'),
    path('delete_blog/<int:pk>', views.deleteBlog, name='delete_blog'),
]

projects/urls.py
from django.urls import path

from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.index, name='projects'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create_projects/', views.create_projects, name='create_projects'),
    path('edit_projects/<int:pk>', views.editOur_project.as_view(), name='edit_projects'),
    path('update_projects/<int:pk>', views.updateOur_project, name='update_projects'),
    path('delete_projects/<int:pk>', views.delete_projects, name='delete_projects'),
]

projects/models.py
from django.db import models

# Create your models here.
from django.db import models
from mdeditor.fields import MDTextField

class Our_Project(models.Model):
    title = models.CharField(max_length=100)
    content = MDTextField()

projects/forms.py
from django.forms import ModelForm


from projects.models import Our_Project

class Our_ProjectForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['title'].widget.attrs['class'] = 'form-control'
        

    class Meta:
        model = Our_Project
        fields = '__all__'

projects/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import TemplateView

from .models import Our_Project
from .forms import Our_ProjectForm


from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import markdown

# Create your views here.
def index(request):
    projects = Our_Project.objects.all()
    context = {'projects': projects}

    return render(request, 'projects/index.html', context)


def detail(request, pk):
    projects = Our_Project.objects.get(pk=pk)
    context = {'projects': projects}

    return render(request, 'projects/detail.html', context)



def create_projects(request):
    form = Our_ProjectForm

    if request.method == 'POST':
        form = Our_ProjectForm(request.POST)

        if form.is_valid():
            form.save()

        return redirect("projects:projects")

    context = {'form': form}

    return render(request, 'projects/create_projects.html',context)


class editOur_project(TemplateView):
    template_name = 'projects/edit_projects.html'

    def get_context_data(self, *args, **kwargs):
        projects = Our_Project.objects.get(pk=self.kwargs.get('pk'))
        context = super().get_context_data(*args, **kwargs)

        context['form'] = Our_ProjectForm(instance=projects)
        context['projects'] = projects

        return context




def updateOur_project(request, *args, **kwargs):
    pk = kwargs.get('pk')

    projects = Our_Project.objects.get(pk=pk)

    title = request.POST['title']

    content = request.POST['content']

    projects.title = title
    projects.content = content

    projects.save()

    return HttpResponseRedirect(
        reverse("projects:projects"))



def delete_projects(request, *args, **kwargs):
    pk = kwargs.get('pk')
    d_our_project = Our_Project.objects.get(pk=pk)
    d_our_project.delete()

    return HttpResponseRedirect(
        reverse("projects:projects"))

projects/templates/projects/create_projects.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
<style>
    body {
        background-color: #ffffff; /* Set background color to white */
    }
</style>
<link rel="stylesheet" type="text/css" href="/static/styles/edit_achievement.css">
<br><br><br><br>
<h2 >Create a new project </h2><br>
<form action="" method="POST" enctype="multipart/form-data" id="myForm">
    {% csrf_token %}
        {{  form.media }}
        {{  form.as_p }}
    <!--
    Title: <input type="text" class="title-input"  name="title"  required/><br/><br>
    Author: <input type="text" class="title-input" name="author" required/><br/><br>
    Content: <br/>
    <textarea cols="57" rows="8" name="content" required></textarea><br/>
    -->
    <input type="submit" class="edit-button1" value="Post"/>
</form>

<script>
    document.getElementById('myForm').addEventListener('submit', function (event) {
        event.preventDefault(); // Prevent the default form submission

        Swal.fire({
            title: 'Are you sure?',
            text: 'You are about to submit this form.',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, submit it!'
        }).then((result) => {
            if (result.isConfirmed) {
                // If the user confirms, submit the form
                document.getElementById('myForm').submit();
            }
        });
    });
</script>
{% endblock content %}

projects/templates/projects/detail.html
{% extends 'base.html' %}

{% load blog_extras %}

{% block content %}
<link rel="stylesheet" type="text/css" href="/static/styles/about.css">
    
    <br><br><br><br>
    <div class="box">
        <section class="overview-section">
            <div class="overview-text">
                <h1 class="title">{{ projects.title }}</h1>

                    {{ projects.content|convert_markdown|safe }}


            </div>
            <!-- </div> -->
        </section>


    </div>
{% endblock %}

projects/templates/projects/edit_projects.html
{% extends 'base.html' %}

{% load blog_extras %}

{% block content %}
    <style>
        /* Style to make input look like textarea */
        .textarea-like-input {
            border: 1px solid #ccc;
            padding: 5px;
            font-size: 16px;
            width: 300px; /* Adjust the width as needed */
            height: 100px; /* Adjust the height as needed */
            resize: none; /* Disable textarea resizing */
        }
    </style>


    <link rel="stylesheet" type="text/css" href="/static/styles/edit_achievement.css">
    <br><br><br>
    <h1>Edit Project </h1>
    <form action="{% url 'projects:update_projects' pk=projects.pk %}" method="POST" enctype="multipart/form-data" id="myForm">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}

        <input type="submit" value="Accept" class="edit-button">

        <input type="button" onclick="deleteContent()" value="delete" class="edit-button1">
        <input type="button" onclick="cancel()" value="cancel" class="edit-button2">


    </form>

    


    <script>
        function sleep(ms) {
            return new Promise(resolve => setTimeout(resolve, ms));
        }

        function cancel() {
            window.location.href =
            {%  url 'projects:projects' %}
        }

        document.getElementById('myForm').addEventListener('submit', function (event) {
            event.preventDefault(); // Prevent the default form submission

            Swal.fire({
                title: 'Are you sure?',
                text: 'You are about to submit this form.',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, submit it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    // If the user confirms, submit the form
                    document.getElementById('myForm').submit();
                }
            });
        });

        function deleteContent() {
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success',
                    cancelButton: 'btn btn-danger'
                },
                buttonsStyling: false
            })

            swalWithBootstrapButtons.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                reverseButtons: true
            }).then((result) => {
                if (result.isConfirmed) {

                    fetch('{% url 'projects:delete_projects' pk=projects.pk %}')
                        .then(response => {
                            if (!response.ok) {
                                throw new Error('Network response was not ok');
                            }
                            return response.json();
                        })
                        .then(data => {
                            console.log(data.message);
                        })
                } else if (
                    /* Read more about handling dismissals below */
                    result.dismiss === Swal.DismissReason.cancel

                ) {
                    swalWithBootstrapButtons.fire(
                        'Cancelled',
                        'Your imaginary file is safe :)',
                        'error'
                    )
                }
            }).then(function () {
                setTimeout(function () {
                    window.location.href =
                    {%  url 'projects:projects' %}
                }, 1000);
            })
        }

    </script>


{% endblock content %}

projects/templates/projects/index.html
{% extends 'base.html' %}

{% block content %}

<link rel="stylesheet" type="text/css" href="/static/styles/about.css">
<div class="container">
  <br>
  <br>
  <h1 style="color: #ffffff;">Our Projects </h1>
  {% for i in projects reversed %}

    <div class="box">
        <section class="overview-section">
            <div class="overview-text">
                <h2 class="title">{{ i.title }}</h2>

                <p class="subtitle" >{{ i.author }}</p>
                <p class="subtitle">{{ i.created_at|date:"Y-m-d H:i" }}</p>
                <a href="{{ i.id }}"><class="read-more">Read more</a><br>
            </div>
            <div class="overview-image">
                <img src="{{ i.image }}">
                {% if user.is_authenticated %}

                <a href='{% url 'projects:edit_projects' pk=i.id %}'>
                    <button type="button" class="edit-button">Edit post</button>
                </a>


                {% endif %}
            </div>
        </section>


    </div>


    {% endfor %}
</div>



{% endblock content %}

projects/templates/projects/our_project.html
{% load staticfiles %}
<! DOCTYPE html>
<html lang = "en">
    <head>
        <meta http-equiv = "Content-Type" content = "text / html; charset = utf-8" />

    </head>
    <body>
        <form method = "post" action = "./">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <p> <input type = "submit" value = "post"> </p>
        </form>
    </body>
</html>